version: '3.8'

services:
  pathhelm:
    build: .
    ports:
      - "8000:8000"
    # PathHelm now depends on both redis and the backend
    depends_on:
      - mock-backend
      - redis

  mock-backend:
    image: python:3.11-slim
    command: >
      sh -c "pip install Flask && python /app/mock_service.py"
    volumes:
      - ./mock_service.py:/app/mock_service.py

  # --- Add this new service ---
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379" # Expose Redis port for potential local debugging
    volumes:
      - ./redis-data:/data