services:
  pathhelm:
    build: .
    ports:
      - "8000:8000"
    # PathHelm now depends on both redis and the backend
    depends_on:
      - mock-backend
      - redis

    env_file:
      - .env

  mock-backend:
    image: python:3.11-slim
    command: >
      sh -c "pip install Flask && python /app/mock_service.py"
    volumes:
      - ./mock_service.py:/app/mock_service.py

  # --- Add this new service ---
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379" # Expose Redis port for potential local debugging
    volumes:
      - ./redis-data:/data

  dashboard:
    build:
      context: .
      # Use the same Dockerfile but run a different command
    command: streamlit run dashboard.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501" # Expose the Streamlit port
    depends_on:
      - pathhelm