services:
  pathhelm:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mock-backend
      - redis
    env_file:
      - .env

  mock-backend:
    image: python:3.11-slim
    command: >
      sh -c "pip install Flask && python /app/mock_service.py"
    volumes:
      - ./mock_service.py:/app/mock_service.py

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  dashboard:
    build:
      context: .
    command: streamlit run dashboard.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - pathhelm
    env_file:
      - .env
    volumes:
      - ./history-data:/code/history-data

  history-collector:
    build:
      context: .
    environment: # ADDED: Force Python output unbuffered
      - PYTHONUNBUFFERED=1
    # MODIFIED: Change command for debugging
    command: >
      sh -c "ls -l /code/ && python /code/history_collector.py"
    depends_on:
      - pathhelm
      - redis
    env_file:
      - .env
    volumes:
      # Ensure the history_collector.py itself is mounted directly for consistency
      - ./history_collector.py:/code/history_collector.py
      # Mount the history-data directory for the SQLite DB
      - ./history-data:/code/history-data

volumes:
  history-data: # Define the named volume