# docker-compose.yml
version: '3.8'

services:
  pathhelm:
    build: .
    ports:
      - "8000:8000"
    # This service depends on the mock-backend to be running
    depends_on:
      - mock-backend

  mock-backend:
    # We don't need a Dockerfile for this simple service
    image: python:3.9-slim
    # On start, install Flask and run the mock_service.py file
    command: >
      sh -c "pip install Flask && python /app/mock_service.py"
    volumes:
      - ./mock_service.py:/app/mock_service.py